include $(DWMAKE)/makedefs

COMPILER_INCLUDE += -I$(THISDIR)/../../include
CXXFILES = main.cpp

LIBS = -L/usr/local/lib64 -losgSprites -losg -losgViewer -losgDB

EXEC = sprites
include $(DWMAKE)/makerules
